language: python

python: 2.7.11

branches:
    only: master

build:
    pre_ci:
        pip install --upgrade coinmarketcap_wrapper
        pip install --upgrade pytest
    ci:
        - coverage run
        - pytest

notifications:
    email: false
