language: python

python: 2.7

branches:
    only: master

build:
    ci:
        - pip install --upgrade cmcwrap
        - pip install --upgrade pytest
        - mkdir -p shippable/codecoverage
        - mkdir -p shippable/testresults
        - pytest --junitxml=shippable/testresults/nosetests.xml
        - pytest --cov=modules --cov-report=xml:shippable/codecoverage/coverage.xml

integrations:
    notification:
        integrationName: irc-integration
        type: irc
        recipients: 'chat.freenode.net#cmcwrap'
        on_pull_request: always
        on_success: always
        on_failure: always
        on_cancel: always
        on_start: never
