language: python

python: 2.7

branches:
    only: master

build:
    ci:
        - pip install --upgrade cmcwrap
        - pip install --upgrade pytest
        - coverage run cmcwrap/test/test_core.py
        - coverage xml -o shippable/codecoverage/coverage.xml
        - pytest
    on_success:
        - echo 'build success'
        - ./clean.sh
    on_failure:
        - echo 'build failure'

notifications:
    email: false
