language: python

python: 2.7.11

branches:
    only: master

build:
    pre_ci:
        pip install --upgrade wrapper-py-coinmarketcap
    ci:
        python tests/test.py

notifications:
    email: false
